### ISSUE TITLE
Enhnacing Backend

### ISSUE THREAD

**Issue by ChetanH358** [serlesen/fullstack-jwt#1]
Enhanced Backend by providing more functionalities as it is returning only 2 responses

**Comment by serlesen** [comment]
The project has 2 tags: chapter_1 and chapter_2. I have two videos linked to this project, but the link on each description goes to a specific tag. If you want to clone the project, checkout the adecuate tag, 1 for React or 2 for Angular. The backend is always with Spring Boot.
